---

- name: Include variables
  vars:
  include_vars:
    file: ../defaults/main.yml

- name: Create folder
  file:
    path: "/etc/ssl/vars"
    state: directory
    mode: 0700

- name: Certificate file check
  stat:
    path: "{{ parent_dir }}/issued/{{ansible_hostname}}.crt"
  register: certs_build

- name: vars configuraion
  template:
    src=../templates/vars.j2
    dest="/etc/ssl/vars/vars.{{ansible_hostname}}"

- name: init-pki
  shell: "/opt/easy-rsa/easyrsa3/easyrsa --batch --vars=/etc/ssl/easyrsa/vars --pki-dir=/etc/ssl/easyrsa init-pki"
  when: certs_build.stat.exists != True

- name: build-ca
  shell: "/opt/easy-rsa/easyrsa3/easyrsa --batch --vars=/etc/ssl/easyrsa/vars --pki-dir=/etc/ssl/easyrsa build-ca nopass"
  when: certs_build.stat.exists != True

- name: server cert and key creation
  shell: "/opt/easy-rsa/easyrsa3/easyrsa --batch --vars=/etc/ssl/easyrsa/vars --pki-dir=/etc/ssl/easyrsa build-server-full {{ ansible_hostname }} nopass"
  when: certs_build.stat.exists != True
