---

- name: Include variables
  vars:
  include_vars:
    file: ../defaults/main.yml

- name: Create folder
  file:
    path: "/etc/ssl/vars"
    state: directory
    mode: 0700

- name: Certificate file check
  stat:
    path: "{{ parent_dir }}/issued/{{certification_name}}.crt"
  register: certs_build

- name: dh.pem file check
  stat:
    path: "{{ parent_dir }}/dh.pem"
  register: dhpem_build

- debug:
    msg: dhpem_build.stat

- name: vars configuraion
  template:
    src=../templates/vars.j2
    dest="/etc/ssl/vars/vars.{{certification_name}}"

- name: Building certs
  shell: "/opt/easy-rsa/easyrsa3/easyrsa --batch --vars=/etc/ssl/vars/vars.{{certification_name}} --pki-dir=/etc/ssl/{{ certification_name}} {{ item }}"
  when: certs_build.stat.exists != True
  with_items:
    - "init-pki"
    - "build-ca nopass"
    - "build-server-full {{ certification_name}} nopass"


- name: Build dhpem file
  shell: "export EASYRSA_KEY_SIZE={{ easy_rsa_keys.size }} && /opt/easy-rsa/easyrsa3/easyrsa --batch --vars=/etc/ssl/vars/vars.{{certification_name}} --pki-dir=/etc/ssl/{{ certification_name}} gen-dh"
  when: easy_rsa_keys.dhpem is defined and dhpem_build.stat.exists != true
