---

- name: Include variables
  vars:
  include_vars:
    file: ../defaults/main.yml

- name: Create folder
  file:
    path: "/etc/ssl/vars"
    state: directory
    mode: 0700

- name: Certificate file check
  stat:
    path: "{{ parent_dir }}/issued/{{certification_name}}.crt"
  register: certs_build

- name: vars configuraion
  template:
    src=../templates/vars.j2
    dest="/etc/ssl/vars/vars.{{certification_name}}"

- name: Building certs
  shell: "/opt/easy-rsa/easyrsa3/easyrsa --batch --vars=/etc/ssl/vars/vars.{{certification_name}} --pki-dir=/etc/ssl/{{ certification_name}} {{ item }}"
  when: certs_build.stat.exists != True
  with_items:
    - "init-pki"
    - "build-ca nopass"
    - "build-server-full {{ certification_name}} nopass"



#- name: init-pki
#  shell: "/opt/easy-rsa/easyrsa3/easyrsa --batch --vars=/etc/ssl/vars/vars.{{certification_name}}" --pki-dir=/etc/ssl/{{ certification_name}} init-pki"
#  when: certs_build.stat.exists != True

#- name: build-ca
#  shell: "/opt/easy-rsa/easyrsa3/easyrsa --batch --vars=/etc/ssl/vars/vars.{{certification_name}}" --pki-dir=/etc/ssl/{{ certification_name}} build-ca nopass"
#  when: certs_build.stat.exists != True

#- name: server cert and key creation
#  shell: "/opt/easy-rsa/easyrsa3/easyrsa --batch --vars=/etc/ssl/vars/vars.{{certification_name}} --pki-dir=/etc/ssl/{{ certification_name}} build-server-full {{ certification_name}} nopass"
#  when: certs_build.stat.exists != True
