Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.define "easyrsa" do |easyrsa|
     easyrsa.vm.hostname = "easyrsa"
     easyrsa.vm.network "public_network", dev: "wlp4s0:", bridge: "wlp4s0:"
     easyrsa.vm.provision :ansible do |ansible|
       ansible.limit = "all"
     #  ansible.inventory_path = "test/hosts/vagrant"
       ansible.playbook = "../main.yml"
    end
  end
end
